-- need to change query
--insert into item (average_completion_time,is_cancelable,is_repeatable,item_price,item_solid_price,max_order_quantity,min_order_quantity,created_at,item_id,modified_at,item_type) values (60,false,false,240000,300000,100,10,now(),1,now(),'YOUTUBE');
--insert into item (average_completion_time,is_cancelable,is_repeatable,item_price,item_solid_price,max_order_quantity,min_order_quantity,created_at,item_id,modified_at,item_type) values (2,false,false,150000,200000,600,1,now(),2,now(),'FACE_BOOK');
