spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  flyway:
#    enabled: true
#    baseline-on-migrate: true