spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        hbm2ddl:
          import_files: classpath:db/dummy.sql
        connection:
          charSet: UTF-8
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  flyway:
#    enabled: true
#    baseline-on-migrate: true

