spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        hbm2ddl:
          import_files: classpath:db/dummy.sql
        connection:
          charSet: UTF-8
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  flyway:
#    enabled: true
#    baseline-on-migrate: true

external:
  real-site:
    url: test.com

payment:
  toss:
    test_client_api_key: test_ck_DpexMgkW36N7Z4OJ7Op93GbR5ozO
    test_secret_api_key: test_sk_ex6BJGQOVDWPqEPYZqPq3W4w2zNb
    success_url: "http://localhost:8080/charge/toss/sucess"
    fail_url: "http://localhost:8080/charge/toss/fail"

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'snsclick-be-main-spring-book-jwt-spring-security-snsclick-be-main-spring-book-jwt-spring-security' 이라는 문자열을 base64로 인코딩
  secret: c25zY2xpY2stYmUtbWFpbi1zcHJpbmctYm9vay1qd3Qtc3ByaW5nLWJvb2stand0LXNwcmluZy1zZWN1cml0eQ==
  token-validity-in-seconds: 3600  # 1시간 (초)
  token-refresh-validity-in-seconds: 1209600  #14일
  
