spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        hbm2ddl:
          import_files: classpath:db/dummy.sql
        connection:
          charSet: UTF-8
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
#  flyway:
#    enabled: true
#    baseline-on-migrate: true

external:
  real-site:
    url: test.com

payment:
  toss:
    test_client_api_key: test_ck_DpexMgkW36N7Z4OJ7Op93GbR5ozO
    test_secret_api_key: test_sk_ex6BJGQOVDWPqEPYZqPq3W4w2zNb
    success_url: "http://localhost:8080/charge/toss/sucess"
    fail_url: "http://localhost:8080/charge/toss/fail"

